---
- name: Install Galaxy Pasteur
  hosts: ifb
  remote_user: root

  roles:
    - {role: ifb, tags: ['ci']}
    - {role: system_dependancies, tags: ['system']}
    - {role: postgresql, tags: ['postgresql']}
    - {role: apache, tags: ['apache']}
    - {role: galaxy, tags: ['galaxy']}
    - {role: python, tags: ['python']}
    - {role: python_dependancies, tags: ['python']}
    - {role: galaxy_conf, tags: ['galaxy_conf']}
    - {role: galaxy_reporting_conf, tags: ['galaxy_reproting_conf']}
#    - {role: galaxy_tools, tags: ['galaxy_tools']}
    - {role: phylogeny_tools, tags: ['phylo_tools']}
    - {role: cleanup, tags: ['clean']}
