- name: Configure Galaxy vhost
  template: src=apache_galaxy.conf.j2 dest=/etc/httpd/conf.d/galaxy.conf mode=0640
  notify:
    - restart httpd

- name: Ensure that apache work with NameVirtualhost
  lineinfile:
    dest=/etc/httpd/conf/httpd.conf
    regexp='^#?NameVirtualHost'
    line='NameVirtualHost *:80'
    state=present

- name: Ensure apache is running and enabled
  service: name=httpd state=running enabled=yes

